AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/FormatStringToken:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
